# Generated by Django 5.0.7 on 2025-10-18 06:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('surname', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('In work', 'In Work'), ('Agree', 'Agree'), ('Disagree', 'Disagree'), ('Dubbing', 'Dubbing')], default='New', max_length=20)),
                ('course', models.CharField(blank=True, choices=[('FS', 'Fs'), ('QACX', 'Qacx'), ('JCX', 'Jcx'), ('JSCX', 'Jscx'), ('FE', 'Fe'), ('PCX', 'Pcx')], max_length=50, null=True)),
                ('course_type', models.CharField(blank=True, choices=[('pro', 'Pro'), ('minimal', 'Minimal'), ('premium', 'Premium'), ('incubator', 'Incubator'), ('vip', 'Vip')], max_length=50, null=True)),
                ('course_format', models.CharField(blank=True, choices=[('static', 'Static'), ('online', 'Online')], max_length=50, null=True)),
                ('sum', models.IntegerField(blank=True, null=True)),
                ('alreadyPaid', models.IntegerField(blank=True, null=True)),
                ('utm', models.CharField(blank=True, max_length=255, null=True)),
                ('msg', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
